import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import "react-color-palette/css";
import { Toaster } from "@/components/ui/toaster";

const font = IBM_Plex_Mono({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} h-screen w-screen`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
